### ISSUE TITLE
Togglz not useable without togglz-console dependency

### ISSUE THREAD

**Issue by hgramlich** [togglz/togglz#309]
We are currently using togglz without the console dependency. After updating from 2.4.1.Final to 2.6.1.Final the application wont start.
`2018-12-06 09:42:54.660 ERROR 4069 --- [ost-startStop-1] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'togglzConsole' defined in class path resource [org/togglz/spring/boot/actuate/autoconfigure/TogglzManagementContextConfiguration$TogglzConsoleConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'togglzConsole' threw exception; nested exception is java.lang.NoClassDefFoundError: `

The autoconfiguration seems to be broken at this point.

Workaround: Add the console dependency and disable it.

**Comment by chkal** [comment]
@ruifigueira Any idea?

**Comment by ruifigueira** [comment]
@hgramlich , I'll try to look at it this weekend. Can you meanwhile provide more of that log / stacktrace, because the log you appended ends with `java.lang.NoClassDefFoundError: ` and normally after that it says the class that failed.

**Comment by ruifigueira** [comment]
@hgramlich, I couldn't reproduce the issue. Can you send the log?

**Comment by hgramlich** [comment]
```
`2018-12-12 10:40:51.639  INFO 16997 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 31341 (http)
2018-12-12 10:40:51.640  INFO 16997 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-12-12 10:40:51.641  INFO 16997 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.34
2018-12-12 10:40:51.650  INFO 16997 --- [ost-startStop-1] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring embedded WebApplicationContext
2018-12-12 10:40:51.650  INFO 16997 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 82 ms
2018-12-12 10:40:51.672  INFO 16997 --- [ost-startStop-1] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class org.togglz.spring.boot.actuate.autoconfigure.TogglzManagementContextConfiguration$TogglzConsoleConfiguration$$EnhancerBySpringCGLIB$$a58ccae8: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
2018-12-12 10:40:51.674 ERROR 16997 --- [ost-startStop-1] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'togglzConsole' defined in class path resource [org/togglz/spring/boot/actuate/autoconfigure/TogglzManagementContextConfiguration$TogglzConsoleConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'togglzConsole' threw exception; nested exception is java.lang.NoClassDefFoundError: org/togglz/console/TogglzConsoleServlet
2018-12-12 10:40:51.676  INFO 16997 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-12-12 10:40:51.690  WARN 16997 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2018-12-12 10:40:51.692  WARN 16997 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2018-12-12 10:40:51.692 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Auditevents' from the JMX domain
2018-12-12 10:40:51.692 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Beans' from the JMX domain
2018-12-12 10:40:51.692 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Health' from the JMX domain
2018-12-12 10:40:51.692 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Conditions' from the JMX domain
2018-12-12 10:40:51.692 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Configprops' from the JMX domain
2018-12-12 10:40:51.692 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Env' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Info' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Liquibase' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Loggers' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Threaddump' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Metrics' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Scheduledtasks' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Httptrace' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Mappings' from the JMX domain
2018-12-12 10:40:51.693 DEBUG 16997 --- [           main] o.s.b.a.e.jmx.JmxEndpointExporter        : Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Togglz' from the JMX domain
2018-12-12 10:40:51.693  INFO 16997 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-12-12 10:40:51.694  INFO 16997 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2018-12-12 10:40:51.695  INFO 16997 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2018-12-12 10:40:51.696  INFO 16997 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2018-12-12 10:40:51.697  INFO 16997 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2018-12-12 10:40:51.698  INFO 16997 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]

Process finished with exit code 1
`
```

**Comment by ruifigueira** [comment]
@hgramlich, thanks, I just got what I needed: it's the `org/togglz/console/TogglzConsoleServlet` that's missing and therefore making it fail.

We should definitely prevent `TogglzConsoleConfiguration` from being loaded if `TogglzConsoleServlet` cannot be found. I'll investigate that.

**Comment by ruifigueira** [comment]
Ok, I guess I know where the problem comes from. In [Spring `@Conditional`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Conditional.html) javadocs it states that:

> NOTE: Inheritance of @Conditional annotations is not supported; any conditions from superclasses or from overridden methods will not be considered. In order to enforce these semantics, @Conditional itself is not declared as @Inherited; furthermore, any custom composed annotation that is meta-annotated with @Conditional must not be declared as @Inherited.

And I have a `@ConditionalOnClass(TogglzConsoleServlet.class)` declared in the parent class. So I need to refactor those `@Conditional` annotations to fix this.

**Comment by ruifigueira** [comment]
@hgramlich, I just fixed the issue in #312. I tried it exluding Togglz console from classpath and now it loads properly. Feel free to try it. 

I won't merge it yet, in case you still find some issue.
